fix: linkage errors due to missing __real___cxa_free_exception and other symbols
    /usr/bin/ld: libbitcoin_util.a(libbitcoin_util_a-stacktraces.o): in function `__wrap___cxa_free_exception':
    /DASH/src/stacktraces.cpp:608:(.text+0x1f74): undefined reference to `__real___cxa_free_exception'
    /usr/bin/ld: libbitcoin_util.a(libbitcoin_util_a-stacktraces.o): in function `__wrap___cxa_allocate_exception':
    /DASH/src/stacktraces.cpp:599:(.text+0x325d): undefined reference to `__real___cxa_allocate_exception'
    /usr/bin/ld: libbitcoin_util.a(libbitcoin_util_a-stacktraces.o): in function `__wrap___assert_fail':
    /DASH/src/stacktraces.cpp:664:(.text+0x6a3d): undefined reference to `__real___assert_fail'
    collect2: error: ld returned 1 exit status

    /usr/bin/ld: libbitcoin_util.a(libbitcoin_util_a-stacktraces.o): in function `GetStackFrameInfos(std::vector<unsigned long, std::allocator<unsigned long> > const&)':
    /DASH/src/stacktraces.cpp:355:(.text+0x259b): undefined reference to `backtrace_pcinfo'
    /usr/bin/ld: /DASH/src/stacktraces.cpp:138:(.text+0x262a): undefined reference to `backtrace_create_state'