Update mac os build instructions
changed protobuf brew dependancy to protobuf260 because on mac os high sierra brew install protobuf will install protobuf 3.6.0 which is incompatible resulting in  
In file included from ./qt/paymentrequestplus.h:10:
./qt/paymentrequest.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
while running make