libconsensus: adapt API header to be compliant to ANSI C
libconsensus currently can't be used in projects that still use the ANSI
C (=C89/C90) standard, as the header uses single-comments which are only
supported since C99:

```
$ echo '#include "./src/script/bitcoinconsensus.h"\nint main() {}' > consensus_test.c
$ gcc -ansi -c consensus_test.c
In file included from consensus_test.c:1:
./src/script/bitcoinconsensus.h:1:1: error: C++ style comments are not allowed in ISO C90
    1 | // Copyright (c) 2009-2010 Satoshi Nakamoto
      | ^
./src/script/bitcoinconsensus.h:1:1: note: (this will be reported only once per input file)
In file included from consensus_test.c:1:
./src/script/bitcoinconsensus.h:96:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
   96 | #endif // BITCOIN_SCRIPT_BITCOINCONSENSUS_H
      |        ^
```

Fix this by changing all single-line comments by /* ... */ comments instead.