Merge bitcoin/bitcoin#31051: test: remove unused code from `script_tests`
e0287bc4b2d83cefb7af48aef457153d0729bcd4 test: remove unused code from script_tests (fanquake)

Pull request description:

  This has been unused since #29648. Noticed while running a newer version of clang-tidy (19.1.1):
  ```bash
  [127/391][6.2s] /opt/homebrew/opt/llvm/bin/clang-tidy -p=build -quiet --config-file=/bitcoin/src/.clang-tidy /bitcoin/src/test/script_tests.cpp
  bitcoin/src/test/script_tests.cpp:126:25: error: local copy 'tx2' of the variable 'tx' is never modified and never used; consider removing the statement [performance-unnecessary-copy-initialization,-warnings-as-errors]
    126 |     CMutableTransaction tx2 = tx;
        |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
    127 |     BOOST_CHECK_MESSAGE(VerifyScript(scriptSig, scriptPubKey, &scriptWitness, flags, MutableTransactionSignatureChecker(&tx, 0, txCredit.vout[0].nValue, MissingDataBehavior::ASSERT_FAIL), &err) == expect, message);
  512 warnings generated.
  ```

ACKs for top commit:
  maflcko:
    review ACK e0287bc4b2d83cefb7af48aef457153d0729bcd4
  BrandonOdiwuor:
    ACK e0287bc4b2d83cefb7af48aef457153d0729bcd4

Tree-SHA512: f69513d0b898e0e9afad047bcec200707b057e3718a3d35bd479a788a1973e49ee7e5f48feadb8731ab5fdbd12a2b53b0bcf65296701e2296c3fdb67cdcabfb5