Merge #7317: fix: drop `virtual` specifier for `CZMQNotificationInterface` dtor
871405205ee4a3b199d7f5279602ddd69ced5ed5 fix: drop `virtual` specifier for `CZMQNotificationInterface` dtor (UdjinM6)

Pull request description:

  ## Issue being fixed or feature implemented
  ```
  In file included from zmq/zmqnotificationinterface.cpp:5:
  ./zmq/zmqnotificationinterface.h:22:13: error: virtual method '~CZMQNotificationInterface' is inside a 'final' class and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
     22 |     virtual ~CZMQNotificationInterface();
        |             ^
  1 error generated.
  ```

  ## What was done?

  ## How Has This Been Tested?

  ## Breaking Changes

  ## Checklist:
  - [ ] I have performed a self-review of my own code
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have added or updated relevant unit/integration/functional/e2e tests
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have assigned this pull request to a milestone _(for repository code-owners and collaborators only)_

ACKs for top commit:
  knst:
    utACK 871405205ee4a3b199d7f5279602ddd69ced5ed5

Tree-SHA512: 9026c7902b7cc7db51925e97212cf54ef98aca98d862911cbdc85cc9828bec07163e9b7258b91d1af4752c2df7962ec85f22933abcf13337506f3b6a78ea279d