rpc: add missing negative capability on blockToJSON()
Fix the following:

```
rpc/blockchain.cpp:150:5: error: calling function 'AssertLockNotHeldInternal<AnnotatedMixin<std::__1::recursive_mutex>>' requires negative capability '!cs_main' [-Werror,-Wthread-safety-analysis]
    AssertLockNotHeld(cs_main); // For performance reasons
    ^
```

Clang 12