fix build error for missing deque
make[2]: Entering directory '/omnicore-src/omnicore-0.9.0/src'
  CXX      omnicored-bitcoind.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-banman.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-blockfilter.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
httpserver.cpp:74:10: error: 'deque' in namespace 'std' does not name a template type
   74 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:33:1: note: 'std::deque' is defined in header '<deque>'; did you forget to '#include <deque>'?
   32 | #include <support/events.h>
  +++ |+#include <deque>
   33 |
httpserver.cpp: In member function 'bool WorkQueue<WorkItem>::Enqueue(WorkItem*)':
httpserver.cpp:92:13: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
   92 |         if (queue.size() >= maxDepth) {
      |             ^~~~~
      |             Enqueue
httpserver.cpp:95:9: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
   95 |         queue.emplace_back(std::unique_ptr<WorkItem>(item));
      |         ^~~~~
      |         Enqueue
httpserver.cpp: In member function 'void WorkQueue<WorkItem>::Run()':
httpserver.cpp:106:35: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
  106 |                 while (running && queue.empty())
      |                                   ^~~~~
      |                                   Enqueue
httpserver.cpp:110:31: error: 'queue' was not declared in this scope; did you mean 'Enqueue'?
  110 |                 i = std::move(queue.front());
      |                               ^~~~~
      |                               Enqueue
make[2]: *** [Makefile:8739: libbitcoin_server_a-httpserver.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/omnicore-src/omnicore-0.9.0/src'
make[1]: *** [Makefile:15166: all-recursive] Error 1
make[1]: Leaving directory '/omnicore-src/omnicore-0.9.0/src'
make: *** [Makefile:788: all-recursive] Error 1