Merge #17849: ci: Fix brew python link
87744b16b02cb9e4f6e97509facf6cc781e60b98 ci: Fix brew python link (Hennadii Stepanov)

Pull request description:

  During the native macOS build on Travis brew-version python update from 3.7.5 to 3.7.6_1 causes link failure:

  ```
  ==> Upgrading python3
  ==> Downloading https://homebrew.bintray.com/bottles/python-3.7.6_1.mojave.bottl
  ==> Downloading from https://akamai.bintray.com/64/643d627c2b4fc03a3286c397d2992
  ######################################################################## 100.0%
  ==> Pouring python-3.7.6_1.mojave.bottle.tar.gz
  Error: The `brew link` step did not complete successfully
  The formula built, but is not symlinked into /usr/local
  ```

  Close #17848

Top commit has no ACKs.

Tree-SHA512: 09164805c557e3bd21df2d0765a1c6815e786040e9ec0e81a916b2df6c4f03974cf92c31eca999b997f8c4ed0998bdd6e35c3de7ccbaaed3bf131521ecc637dc

Former-commit-id: ba29a3ac4e040fcfc7425f275f964c9201cb447a