move-only: IsDeprecatedRPCEnabled to rpc/util to fix builds when called from wallet
CI builds confusingly fail with "undefined reference to IsDeprecatedRPCEnabled
in libbitcoin_wallet" compiler errors when this function is called from wallet
RPCs.

Fix this by moving IsDeprecatedRPCEnabled() from rpc/server to rpc/util,
thereby moving it from node to common to be picked up by libbitcoin_wallet
(see doc/design/librairies.md and src/Makefile.am).