contrib: continue if binary is None in {security,symbol}-check.py scripts
as the code in that iteration should not proceed in the absence of a binary.

This also fixes the following errors reported by recent releases of the python linter:

contrib/devtools/symbol-check.py:298: error: Item "None" of "Binary | None" has no attribute "format"  [union-attr]
contrib/devtools/security-check.py:253: error: Item "None" of "Binary | None" has no attribute "format"  [union-attr]
contrib/devtools/security-check.py:254: error: Item "None" of "Binary | None" has no attribute "abstract"  [union-attr]
contrib/devtools/security-check.py:255: error: Item "None" of "Binary | None" has no attribute "concrete"  [union-attr]