test: fix intermittert error in feature_asset_locks.py due to missing IS quorum
2025-05-15T19:50:51.884000Z TestFramework (INFO): Test no IS for asset unlock...
2025-05-15T19:50:52.892000Z TestFramework (INFO): Send tx with expected_error:'None'...
2025-05-15T19:51:54.214000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''
        def check_instantlock():
            self.bump_mocktime(1)
            try:
                return node.getrawtransaction(txid, True)["instantlock"]
            except:
                return False
'''
2025-05-15T19:51:54.214000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/knst/projects/dash-v21/test/functional/test_framework/test_framework.py", line 162, in main
    self.run_test()
  File "/home/knst/projects/dash-v21/test/functional/feature_asset_locks.py", line 266, in run_test
    self.test_asset_unlocks(node_wallet, node, pubkey)
  File "/home/knst/projects/dash-v21/test/functional/feature_asset_locks.py", line 373, in test_asset_unlocks
    self.wait_for_instantlock(is_id, node)
  File "/home/knst/projects/dash-v21/test/functional/test_framework/test_framework.py", line 1655, in wait_for_instantlock
    if self.wait_until(check_instantlock, timeout=timeout, sleep=1, do_assert=expected) and not expected:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/knst/projects/dash-v21/test/functional/test_framework/test_framework.py", line 902, in wait_until
    return wait_until_helper(test_function, timeout=timeout, lock=lock, timeout_factor=self.options.timeout_factor, sleep=sleep, do_assert=do_assert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/knst/projects/dash-v21/test/functional/test_framework/util.py", line 287, in wait_until_helper
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
AssertionError: Predicate ''''
        def check_instantlock():
            self.bump_mocktime(1)
            try:
                return node.getrawtransaction(txid, True)["instantlock"]
            except:
                return False
''' not true after 60.0 seconds
2025-05-15T19:51:54.265000Z TestFramework (INFO): Stopping nodes

 node3 2025-05-15T19:50:54.054321Z (mocktime: 2014-12-04T18:19:47Z) [ scheduler] [llmq/signing.cpp:712] [AsyncSignIfMember] [llmq] CSigningManager::AsyncSignIfMember -- failed to select quorum. id=ce79d1f19020ec65caa8a81306362ddad6ffd0e6fc45e18c83630f401b38d54c, msgHash=83b6e8b1549ad9f2750e13e61aabdf08fd31eb1e80cbbd3729920c4c840318ae
 node2 2025-05-15T19:50:54.054326Z (mocktime: 2014-12-04T18:19:47Z) [ scheduler] [llmq/signing.cpp:712] [AsyncSignIfMember] [llmq] CSigningManager::AsyncSignIfMember -- failed to select quorum. id=ce79d1f19020ec65caa8a81306362ddad6ffd0e6fc45e18c83630f401b38d54c, msgHash=83b6e8b1549ad9f2750e13e61aabdf08fd31eb1e80cbbd3729920c4c840318ae