Update build-windows.md
On a fresh and fully updated install of Ubuntu 16.04 LTS, and exactly following the outlined installation instruction for win64bit, in step "make":
  CXX      qt/qt_bitcoin_qt-bitcoin.o   error: #error This file was generated by a newer version of protoc 
fatal error: google/protobuf/arena.h: No such file or directory #include <google/protobuf/arena.h>
Is caused by missing protobuf-compiler:
Geert@Linux: protoc --version
The program 'protoc' is currently not installed. You can install it by typing: sudo apt install protobuf-compiler

I can't reproduce the bug mentioned in footnote 1. The compiled bitcoin-cli.exe bitcoind.exe bitcoin-rpc.exe and bitcoin-qt.exe passed a 2 hour test on my fresh install of windows7-64bit. 

Thank you for building x-platform !