test: Avoid ODR-use of `static const` class member variables
These constants are declared `static const` within the respective
classes. Attempting to use them as `const T&` results in a linker
failure, as the code would refer to storage for the variable, which is
not defined yet:

```
undefined reference to `LockedPool::ARENA_SIZE'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

This can be avoided by initializing a variable with the value of this
constant first.