wallet: add missing annotations
Fix the following:

```
src/wallet/bdb.cpp:428:5: error: calling function 'AssertLockNotHeldInternal<AnnotatedMixin<std::__1::recursive_mutex>>' requires negative capability '!cs_db' [-Werror,-Wthread-safety-analysis]
    AssertLockNotHeld(cs_db);
    ^
```

Clang 12