Merge bitcoin/bitcoin#25779: guix: ignore additional failing certvalidator test
4cf3b7d763b0f864c767720141fa928f55065107 guix: ignore additional failing certvalidator test (fanquake)

Pull request description:

  Any Guix build that needs to build the python-certvalidator code will currently fail due to expired certs. So once again ignore the failing tests. Similar to 85885919656a3f606f3d7f208378aabe95f3f62d.

  ```bash
  ERROR: test_revocation_mode_soft (tests.test_validate.ValidateTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/guix-build-python-certvalidator-0.1-1.a145bf2.drv-0/source/tests/test_validate.py", line 85, in test_revocation_mode_soft
      validate_path(context, path)
    File "/tmp/guix-build-python-certvalidator-0.1-1.a145bf2.drv-0/source/tests/../certvalidator/validate.py", line 50, in validate_path
      return _validate_path(validation_context, path)
    File "/tmp/guix-build-python-certvalidator-0.1-1.a145bf2.drv-0/source/tests/../certvalidator/validate.py", line 358, in _validate_path
      raise PathValidationError(pretty_message(
  certvalidator.errors.PathValidationError: The path could not be validated because the end-entity certificate expired 2022-07-27 12:00:00Z
  ```

  Guix Build (arm64):
  ```bash
  b843f87a61eb2a44d085ab99793ff095290436102b19cd6d6d703c281eba539f  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/SHA256SUMS.part
  280c19bd0a6899dd6100e1d6f632ba9e845500f58f59ed7d6703d818ae2780f0  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/bitcoin-4cf3b7d763b0-arm64-apple-darwin-unsigned.dmg
  9b80cc44e3eeeadb2a17bdcf10fcae7cca4bceceec8fb47c2c757a43753a03c6  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/bitcoin-4cf3b7d763b0-arm64-apple-darwin-unsigned.tar.gz
  43d781b61817a8e0c6168d6611ccb9a4242cf7289b4cc4b5ac77484f34d01738  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/bitcoin-4cf3b7d763b0-arm64-apple-darwin.tar.gz
  38d261b70baf018f8a1ee980fb139451b085dc484516562af4b5ae86a0b71869  guix-build-4cf3b7d763b0/output/dist-archive/bitcoin-4cf3b7d763b0.tar.gz
  e5d08f055f73a1abf5eef0ea4e55098a53e859d0ea7ff29d21a78e30204e8b5c  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/SHA256SUMS.part
  2388708d670068515bec06219792f34494ab7ac939999572dc4b5d92430e0890  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/bitcoin-4cf3b7d763b0-x86_64-apple-darwin-unsigned.dmg
  cb43edd02b8eb11c3e9d8bf6baf65b5656577a2f7a2b21374f90c08a196aa608  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/bitcoin-4cf3b7d763b0-x86_64-apple-darwin-unsigned.tar.gz
  6f443713f2e23da705defddc09c8c66743691841e01d0debe29dad442454e5c8  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/bitcoin-4cf3b7d763b0-x86_64-apple-darwin.tar.gz
  ```

  Guix Build (x86_64):
  ```bash
  7e18af2409e9811ea2bb2aa41a19dcc0b4ac626bb5effe30909ef21942bfb611  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/SHA256SUMS.part
  b6ec0c9ca967e1e3301894bb2ac92d1fab663cfd620004c8044a3685deb7c9e5  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/bitcoin-4cf3b7d763b0-arm64-apple-darwin-unsigned.dmg
  9f8de6d555d0922fd1fc970628bd2a9a9d3e6779b458038e18bd9d5dd9633a1b  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/bitcoin-4cf3b7d763b0-arm64-apple-darwin-unsigned.tar.gz
  534b83732ff90bca57e748b25465f8d3d52d653e7ca52cf4ce2226e5bed814fc  guix-build-4cf3b7d763b0/output/arm64-apple-darwin/bitcoin-4cf3b7d763b0-arm64-apple-darwin.tar.gz
  38d261b70baf018f8a1ee980fb139451b085dc484516562af4b5ae86a0b71869  guix-build-4cf3b7d763b0/output/dist-archive/bitcoin-4cf3b7d763b0.tar.gz
  e5d08f055f73a1abf5eef0ea4e55098a53e859d0ea7ff29d21a78e30204e8b5c  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/SHA256SUMS.part
  2388708d670068515bec06219792f34494ab7ac939999572dc4b5d92430e0890  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/bitcoin-4cf3b7d763b0-x86_64-apple-darwin-unsigned.dmg
  cb43edd02b8eb11c3e9d8bf6baf65b5656577a2f7a2b21374f90c08a196aa608  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/bitcoin-4cf3b7d763b0-x86_64-apple-darwin-unsigned.tar.gz
  6f443713f2e23da705defddc09c8c66743691841e01d0debe29dad442454e5c8  guix-build-4cf3b7d763b0/output/x86_64-apple-darwin/bitcoin-4cf3b7d763b0-x86_64-apple-darwin.tar.gz
  ```

ACKs for top commit:
  achow101:
    ACK 4cf3b7d763b0f864c767720141fa928f55065107
  jarolrod:
    ACK https://github.com/bitcoin/bitcoin/commit/4cf3b7d763b0f864c767720141fa928f55065107

Tree-SHA512: fd83e05f5d772cdcd5a92862bd65a85f128492972be0cb441770bcee7764f889f13b1d109988d360bb9b294942c5b14e46258442b1b3fa1b2902ce958015a897