fix: intermittent error in feature_dip3_v19.py
It can happen on Regtest or Devnet if v20 is just activated but the best
chainlock is still in legacy (pre-v19) scheme.

It causes errors on CI similar to this one:

    2025-05-31T10:28:49.821000Z TestFramework (INFO): Checking that protxs with duplicate EvoNodes fields are rejected
    2025-05-31T10:29:50.653000Z TestFramework (INFO): dynamically_prepare_masternode failed
    2025-05-31T10:30:50.784000Z TestFramework (ERROR): Assertion failed
    Traceback (most recent call last):
      File "DASH/test/functional/test_framework/test_framework.py", line 162, in main
        self.run_test()
      File "DASH/test/functional/feature_dip3_v19.py", line 87, in run_test
        self.dynamically_evo_update_service(evo_info_0, 8)
      File "DASH/test/functional/test_framework/test_framework.py", line 1384, in dynamically_evo_update_service
        tip = self.generate(self.nodes[0], 1)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "DASH/test/functional/test_framework/test_framework.py", line 805, in generate
        sync_fun() if sync_fun else self.sync_all()
                                    ^^^^^^^^^^^^^^^
      File "DASH/test/functional/test_framework/test_framework.py", line 874, in sync_all
        self.sync_blocks(nodes)
      File "DASH/test/functional/test_framework/test_framework.py", line 840, in sync_blocks
        raise AssertionError("Block sync timed out after {}s:{}".format(
    AssertionError: Block sync timed out after 60s:
      '4227eea732e686fcf608bcbc5525a02336bb69c2eed70e8a59d6439b2122190f'
      '4227eea732e686fcf608bcbc5525a02336bb69c2eed70e8a59d6439b2122190f'
      '4227eea732e686fcf608bcbc5525a02336bb69c2eed70e8a59d6439b2122190f'
      '4227eea732e686fcf608bcbc5525a02336bb69c2eed70e8a59d6439b2122190f'
      '4227eea732e686fcf608bcbc5525a02336bb69c2eed70e8a59d6439b2122190f'
      '4227eea732e686fcf608bcbc5525a02336bb69c2eed70e8a59d6439b2122190f'
      '0ade04ee0ae89d1168792a65c28956557c9f2991d141180b9faf7a9ae986cf24'
    2025-05-31T10:30:50.837000Z TestFramework (INFO): Stopping nodes

While underlying error is `bad-cbtx-invalid-clsig`:

     2025-05-31T10:28:49.932591Z [util/system.h:57] [error] ERROR: ConnectBlock(DASH): ProcessSpecialTxsInBlock for block 4f8767d0ad2e7c8882ba4b2819a1d8eb29fbc608ff8201ed1c857d6d3ec51cc9 failed with bad-cbtx-invalid-clsig
     2025-05-31T10:28:49.932632Z [validationinterface.cpp:254] [BlockChecked] [validation] BlockChecked: block hash=4f8767d0ad2e7c8882ba4b2819a1d8eb29fbc608ff8201ed1c857d6d3ec51cc9 state=bad-cbtx-invalid-clsig
     2025-05-31T10:28:49.932660Z [validation.cpp:1634] [InvalidChainFound] InvalidChainFound: invalid block=4f8767d0ad2e7c8882ba4b2819a1d8eb29fbc608ff8201ed1c857d6d3ec51cc9  height=202  log2_work=8.665336  date=2014-12-04T17:46:38Z
     2025-05-31T10:28:49.932667Z [validation.cpp:1639] [InvalidChainFound] InvalidChainFound:  current best=0ade04ee0ae89d1168792a65c28956557c9f2991d141180b9faf7a9ae986cf24  height=201  log2_work=8.658211  date=2014-12-04T17:36:30Z