infra: define -DDEBUG_LOCKORDER in configure-itcoin-core.sh, too
Without this change the build is broken due to missing TS_ITCOIN_* symbols, both
in docker and on bare metal.

EXAMPLE:
    ./sync.h:80:104: error: expected initializer before 'EXCLUSIVE_LOCKS_REQUIRED'
       80 | inline void AssertLockHeldInternal(const char* pszName, const char* pszFile, int nLine, MutexType* cs) EXCLUSIVE_LOCKS_REQUIRED(cs) {}
          |                                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~

This should have been part of 8e967962378e.