bench: Implement IS_TRIVIALLY_CONSTRUCTIBLE via __has_trivial_constructor on clang
libcxx, which carries the implementation is apparently unversioned, so
this is an alternative to tracking down the specific version of clang
which switched from has_trivial_default_constructor to
is_trivially_default_constructible.
https://github.com/llvm-mirror/libcxx/commit/2fd6d25bf1758218aa71938ab343dcaefff4ffeb
https://libcxx.llvm.org/

    bench/prevector.cpp:27:21: error: no template named 'is_trivially_default_constructible' in namespace 'std'; did you mean 'has_trivial_default_constructor'?
    static_assert(!std::is_trivially_default_constructible<nontrivial_t>::value,
                   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        has_trivial_default_constructor
    /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:1211:12: note: 'has_trivial_default_constructor' declared here
        struct has_trivial_default_constructor
               ^
    bench/prevector.cpp:31:20: error: no template named 'is_trivially_default_constructible' in namespace 'std'; did you mean 'has_trivial_default_constructor'?
    static_assert(std::is_trivially_default_constructible<trivial_t>::value,
                  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       has_trivial_default_constructor
    /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:1211:12: note: 'has_trivial_default_constructor' declared here
        struct has_trivial_default_constructor
               ^
    2 errors generated.
https://travis-ci.org/Empact/bitcoin/jobs/468866070