refactor: Apply _sats literals (more manual)
Also changes some implicitly bool conditions to != 0_sats.

The reason "/*nValueIn=*/" was removed in src/wallet/test/fuzz/coinselection.cpp was that clang-tidy (mis)matched it with the v-argument for the _sats literal:
/home/runner/work/_temp/src/wallet/test/fuzz/coinselection.cpp:377:45: error: argument name 'nValueIn' in comment does not match parameter name 'v' [bugprone-argument-comment,-warnings-as-errors]
  377 |     const auto dust{GetDustThreshold(CTxOut{/*nValueIn=*/0_sats, change_out_script}, coin_params.m_discard_feerate)};
      |                                             ^
/home/runner/work/_temp/src/consensus/amount.h:136:53: note: 'v' declared here
  136 | constexpr Amount operator""_sats(unsigned long long v)
      |                                                     ^