wallet: move `hdwallet.cpp` to `libbitcoin_wallet.a`
Required to resolve link failures:

```
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
libbitcoin_wallet.a(libbitcoin_wallet_a-rpcwallet.o): in function `getwalletinfo(JSONRPCRequest const&)':
rpcwallet.cpp:(.text+0x4db2d): undefined reference to `CHDChain::CountAccounts()'
/usr/bin/ld: rpcwallet.cpp:(.text+0x4dc15): undefined reference to `CHDChain::CountAccounts()'
/usr/bin/ld: rpcwallet.cpp:(.text+0x4dd42): undefined reference to `CHDChain::GetAccount(unsigned int, CHDAccount&)'
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
libbitcoin_wallet.a(libbitcoin_wallet_a-scriptpubkeyman.o): in function `LegacyScriptPubKeyMan::CheckDecryptionKey(std::vector<unsigned char, secure_allocator<unsigned char> > const&, bool)':
scriptpubkeyman.cpp:(.text+0x1041): undefined reference to `CHDChain::IsNull() const'
/usr/bin/ld: scriptpubkeyman.cpp:(.text+0x1058): undefined reference to `CHDChain::IsNull() const'
/usr/bin/ld: scriptpubkeyman.cpp:(.text+0x11a9): undefined reference to `CHDChain::GetSeedHash()'
/usr/bin/ld: libbitcoin_wallet.a(libbitcoin_wallet_a-scriptpubkeyman.o): in function `LegacyScriptPubKeyMan::DecryptHDChain(std::vector<unsigned char, secure_allocator<unsigned char> > const&, CHDChain&) const':
[...]
rpcdump.cpp:(.text+0x216d8): undefined reference to `CHDChain::GetMnemonic(std::__cxx11::basic_string<char, std::char_traits<char>, secure_allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, secure_allocator<char> >&) const'
/usr/bin/ld: rpcdump.cpp:(.text+0x217a3): undefined reference to `CHDChain::GetSeed() const'
/usr/bin/ld: rpcdump.cpp:(.text+0x21a44): undefined reference to `CHDChain::CountAccounts()'
/usr/bin/ld: rpcdump.cpp:(.text+0x21a6e): undefined reference to `CHDChain::GetAccount(unsigned int, CHDAccount&)'
/usr/bin/ld: rpcdump.cpp:(.text+0x21b80): undefined reference to `CHDChain::CountAccounts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```