http: add missing header bootlegged by boost < 1.72
httpserver.cpp:74:10: error: no template named 'deque' in namespace 'std'
    std::deque<std::unique_ptr<WorkItem>> queue;
    ~~~~~^


Former-commit-id: 6b34366197cb93a4741efcaafe5c1ed2dd0d8f6c