Revert "Remove unused raw-pointer read helper from univalue"
This reverts commit fa940f41eaffa4b2a28c465a10a4c12d4b8976b8.

With this commit produce the following compilation error.

```
Making all in src
make[1]: Entering directory '/home/vincent/Github/bitcoin/src'
make[2]: Entering directory '/home/vincent/Github/bitcoin/src'
make[3]: Entering directory '/home/vincent/Github/bitcoin'
make[3]: Leaving directory '/home/vincent/Github/bitcoin'
  GEN      obj/build.h
  CXX      libbitcoin_util_a-clientversion.o
  AR       libbitcoin_util.a
  CXXLD    bitcoind
  CXXLD    bitcoin-cli
  CXXLD    bitcoin-tx
  CXXLD    bitcoin-wallet
  CXXLD    bitcoin-util
  CXX      test/test_bitcoin-base58_tests.o
test/base58_tests.cpp: In member function ‘void base58_tests::base58_EncodeBase58::test_method()’:
test/base58_tests.cpp:26:44: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘const unsigned char [1462]’
   26 |     UniValue tests = read_json(json_tests::base58_encode_decode);
      |                                ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from test/base58_tests.cpp:8:
./test/util/json.h:12:39: note: in passing argument 1 of ‘UniValue read_json(const std::string&)’
   12 | UniValue read_json(const std::string& jsondata);
      |                    ~~~~~~~~~~~~~~~~~~~^~~~~~~~
test/base58_tests.cpp: In member function ‘void base58_tests::base58_DecodeBase58::test_method()’:
test/base58_tests.cpp:46:44: error: invalid initialization of reference of type ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘const unsigned char [1462]’
   46 |     UniValue tests = read_json(json_tests::base58_encode_decode);
      |                                ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
./test/util/json.h:12:39: note: in passing argument 1 of ‘UniValue read_json(const std::string&)’
   12 | UniValue read_json(const std::string& jsondata);
      |                    ~~~~~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [Makefile:18253: test/test_bitcoin-base58_tests.o] Error 1
make[2]: Leaving directory '/home/vincent/Github/bitcoin/src'
make[1]: *** [Makefile:20006: all-recursive] Error 1
make[1]: Leaving directory '/home/vincent/Github/bitcoin/src'
make: *** [Makefile:815: all-recursive] Error 1
```

The main problem is that we can not auto-convert an unsigned char string to a std::string.