fix: re-resolve conflicts for previous backports in wallet_multiwallet.py after bitcoin/bitcoin#26192
Done to make it unify with Bitcoin Core, re-ordered line, removed duplicates and out-dated lines
Without these changes wallet_multiwallet.py fails with error:

    AssertionError: Expected substring not found in error message:
    substring: 'Wallet "w1" is already loaded.'
    error message: 'Wallet file verification failed. Refusing to load database. Data file 'wallet_multiwallet_213/node0/regtest/wallets/wallet.dat' is already loaded.'.